--CREAR BASE DE DATOS SI NO EXISTE
IF NOT EXISTS(SELECT 1 FROM sys.databases WHERE name = 'BD2_TPI_Biblioteca')
BEGIN
	CREATE DATABASE [BD2_TPI_Biblioteca]
END
GO

--CAMBIAR AL CONTEXTO DE LA BASE DE DATOS CREADA
USE [BD2_TPI_Biblioteca]
GO

--CREAR TABLAS SI NO EXISTEN
IF NOT EXISTS(SELECT 1 FROM sys.tables WHERE name = 'Libros')
BEGIN
	CREATE TABLE Libros(
		IDLibro INT PRIMARY KEY IDENTITY (1,1),
		Titulo NVARCHAR(255) NOT NULL,
		AnioPublicacion INT NULL
	)

	CREATE TABLE Categorias(
		IDCategoria INT PRIMARY KEY IDENTITY (1,1),
		Descripcion NVARCHAR(100) NOT NULL
	)

	CREATE TABLE Autores(
		IDAutor INT PRIMARY KEY IDENTITY (1,1),
		Nombre NVARCHAR(100) NULL,
		Apellido NVARCHAR(100) NULL,
		Seudonimo NVARCHAR(100) NULL,
		--NO PUEDEN SER NULL LOS 3 DATOS A LA VEZ
		CONSTRAINT CHK_Autor_NombreApellidoSeudonimo CHECK(
			Nombre IS NOT NULL OR Apellido IS NOT NULL OR Seudonimo IS NOT NULL
		)
	)

	CREATE TABLE Usuarios(
		IDUsuario INT PRIMARY KEY IDENTITY (1,1),
		DNI NVARCHAR(20) NOT NULL UNIQUE,
		Email NVARCHAR(255) NOT NULL,
		Nombre NVARCHAR(100) NOT NULL,
		Apellido NVARCHAR(100) NOT NULL,
		Telefono NVARCHAR(20) NULL
	)

	CREATE TABLE LibroAutor(
		IDLibro INT NOT NULL,
		IDAutor INT NOT NULL,
		FOREIGN KEY (IDLibro) REFERENCES Libros(IDLibro) ON DELETE CASCADE,
		FOREIGN KEY (IDAutor) REFERENCES Autores(IDAutor) ON DELETE CASCADE,
		PRIMARY KEY (IDLibro, IDAutor)
	)

	CREATE TABLE LibroCategoria(
		IDLibro INT NOT NULL,
		IDCategoria INT NOT NULL,
		FOREIGN KEY (IDLibro) REFERENCES Libros(IDLibro) ON DELETE CASCADE,
		FOREIGN KEY (IDCategoria) REFERENCES Categorias(IDCategoria) ON DELETE CASCADE,
		PRIMARY KEY (IDLibro, IDCategoria)
	)

	CREATE TABLE Ejemplares(
		IDEjemplar INT PRIMARY KEY IDENTITY (1,1),
		IDLibro INT NOT NULL,
		Estado NVARCHAR(50),
		Observaciones NVARCHAR(255),
		FOREIGN KEY (IDLibro) REFERENCES Libros(IDLibro) ON DELETE CASCADE
	)

	CREATE TABLE Prestamos(
		IDPrestamo INT PRIMARY KEY IDENTITY (1,1),
		IDUsuario INT NOT NULL,
		IDEjemplar INT NOT NULL,
		FechaPrestamo DATE NOT NULL,
		FechaDevolucion DATE NOT NULL,
		Devuelto BIT NOT NULL,
		FOREIGN KEY (IDUsuario) REFERENCES Usuarios(IDUsuario) ON DELETE CASCADE,
		FOREIGN KEY (IDEjemplar) REFERENCES Ejemplares(IDEjemplar) ON DELETE CASCADE
	)
END
GO
